name: appli_edt_univ
description: "Application de visionnage de l'emploi du temps de l'UNC."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # https://pub.dev/packages/cupertino_icons
  http: ^1.4.0 # https://pub.dev/packages/http
  icalendar_parser: ^2.1.0 # https://pub.dev/packages/icalendar_parser
  table_calendar: ^3.2.0 # https://pub.dev/packages/table_calendar
  intl: ^0.20.2 # https://pub.dev/packages/intl
  shared_preferences: ^2.5.3 # https://pub.dev/packages/shared_preferences

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # https://pub.dev/packages/flutter_launcher_icons
  change_app_package_name: ^1.5.0 # https://pub.dev/packages/change_app_package_name

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_transparent.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon_transparent.png"
    background_color: "#FFFFFF"
    theme_color: "#1800AD"
  windows:
    generate: true
    image_path: "assets/images/app_icon_transparent.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon_transparent.png"